### ISSUE TITLE
Project feed should include OpsLog entries

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi-ui#30]
The project feed should include OpsLog entries in the timeline.

**Comment by in-op** [comment]
This poses an ordering algorithm problem. The feed component elements must be ordered by timestamp desc. Currently it grabs 25 project fact history changes. If we also grab from another data source, we need to ensure it doesn't run into this situation:

```
set1: 1, 3, 5, 6
set2: 2, 4, 7, 9
```

and we grab limit 3 from each on the first fetch: `1, 3, 5`, and `2, 4, 7`, we can't display `7` because the other set has a preceding value `6` which we don't know about yet.

Something like keeping track of the last-ordered item we know of so-far from each datasource, and only displaying the earlier one (in the example, that's 5) and nothing after it (so not displaying 7), is a solution I've thought of.

Alternatively, you could fetch from both sources with a > timestamp condition, but then you have no clue how many entries you're going to get back, which poses other problems.

And finally, another solution is to collect everything that should be a feed item into a new index, but I'm not sure how graceful that is with varying data accompanying it.
